export const STATUS_CONTENT_SELLER_VIEW = {
  DELIVERED_DETAIL: 'DELIVERED',
  PROCESSING_DETAIL: 'PROCESSING',
  DENY: 'DENY',
  CHANGE_PROFILE: 'CHANGE_PROFILE',
  DETAIL_PROFILE: 'MY_PROFILE',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  LIST_PRODUCT: 'LIST_PRODUCT',
}
